# Generated by Django 3.2.5 on 2021-07-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trgovina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ime', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Delavec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ime', models.CharField(max_length=200)),
                ('Priimek', models.CharField(max_length=200)),
                ('DatumRojstva', models.DateField()),
                ('Spol', models.CharField(max_length=30)),
                ('trgovina', models.ManyToManyField(to='app.Trgovina')),
            ],
        ),
    ]
